kai-dg/hipposcraper

- project-all_scraper.py
- test_file_scraper.py
Defined function `scrape_tests` in file `test_file_scraper.py` that creates test files. Updated `all_scraper` to accordingly call this function.
Also, fixed pathname for `.json` file credentials in `all_scraper`.
> Defining test scraper function and updating all_scraper accordingly

- README.md
- holberton-read_t.py
- also fixed multiple file detection
- added README customization section in repo's README
> added extra scrapes for more README customization

- project-all_scraper.py
- scrapers/c_scraper.py
function scrape_header in main now for debugging purposes
> split create header func into c_scraper

- project-all_scraper.py
- scrapers/c_scraper.py
if no header found, else statement had a bug.
assigned parameter variables before calling and added if statements to catch them in the function itself
> fixed no prototype else statement for c projects

- holberton-read_t.py
fixed task description formatting when inserting each line
> added * in front of each task descript item

- holberton-read_t.py
- project-all_scraper.py
- scrapers/__init__.py
- scrapers/bash_scraper.py
> added bash to main scraper and readme

- README.md
- hipposcrape.sh
- holberton-read_t.py
- project-all_scraper.py
- scrapers/bash_scraper.py
- scrapers/c_scraper.py
- scrapers/py_scraper.py
- scrapers/test_file_scraper.py
Numerous overall updates/improvements:
- Implementing more comprehensive error-handling for `holberton-read_t.py`
- Updating error messages - improving syntax and formatting with fancy-looking arrows/indenting
- Improving performance of `test_scraper.py` (now scrapes shell username and writes text accordingly)
- Updating module-level and function documentation for all files
- Uploading Bash script `hipposcrape.sh` that runs entire scraper simultaneously
- Revamping `README.md` to reflect changes
- General file formatting edits to match `pycodestyle`
> Mini Revamp

- holberton-read_t.py
- project-all_scraper.py
- scrapers/py_scraper.py
- scrapers/test_file_scraper.py
- Removed extra open() in readme scraper
- Added new directory file creation function in py_scraper
- Refactored py_scaper
- Added encoding to string on test_file_scraper
> added dir file creation function, refactored following files

- holberton-read_t.py
- Fixed IndexError on line 221, was checking wrong array
- Changed directory name grabbing method by finding next "li" tag from repo name
- Fixed some error messaging formating
> changed method of grabbing directory name

- scrapers/low_scraper.py
-fixed header creation where it was writing extra ';' on _putchar
> removed ';' in write_header

- scrapers/low_scraper.py
Changed two lines, added ; before the newline character
> Added ; in header file. Semi colons were missing in header files after function prototypes

- README.md
- hippoproject.py
- hipporead.py
- scrapers/low_scraper.py
- scrapers/read_scraper.py
- scrapers/test_file_scraper.py
Fixes for 2 projects:
0x0C. Web stack debugging #0
0x1C. C - Binary trees
C's header writer changed to find `$` instead of `:`
Readme's find learning objectives changed the variable assignment of exception to `""` from `None`
> 1.0.2 update

- README.md
- hippoproject.py
- hipporead.py
- scrapers/high_scraper.py
- setup.sh
Updated `setup.sh`:
-Auto replace on hipposcrape.sh
-Added refresh .bashrc on end of script
Updated `high_scraper.py`:
-Added .sh detection to write bash shebang
> 1.0.5 update

- README.md
- hippoproject.py
- hipporead.py
- scrapers/high_scraper.py
- scrapers/sys_scraper.py
- scrapers/test_file_scraper.py
Updated `high_scraper.py`:
- Added auto node js shebang
Updated `sys_scraper.py`:
- Added try/except for finding task file names when writing task files
Updated `test_file_scraper.py`:
- Added extra conditional (more than 1 newline) for finding test files
> 1.0.6 update

- hippoproject.py
- hipporead.py
- scrapers/base_parse.py
- scrapers/high_scraper.py
- scrapers/low_scraper.py
- scrapers/read_scraper.py
- scrapers/test_file_scraper.py
- Updated manual scraping methods to self init in respective scrapers
> development to version-control

- README.md
- hippoproject.py
- hipporead.py
- requirements.txt
- scrapers/base_parse.py
- scrapers/high_scraper.py
- scrapers/low_scraper.py
- scrapers/read_scraper.py
- scrapers/sys_scraper.py
- scrapers/test_file_scraper.py
A few bug fixes and overall change on self init structure on each scraper.
Updated `base_parse.py`:
- Updated `__init__()` to autoscrape when object is called.
Updated `high_scraper.py`:
- Updated `__init__()` to autoscrape when object is called.
Updated `low_scraper.py`:
- Updated `__init__()` to autoscrape when object is called.
Updated `read_scraper.py`:
- Updated `__init__()` to autoscrape when object is called.
Updated `sys_scraper.py`:
- Updated `__init__()` to autoscrape when object is called.
- Added `.py` shebang detection.
Updated `test_file_scraper.py`:
- Updated `__init__()` to autoscrape when object is called.
Updated `hippoproject.py`:
- Removed manual scraping methods.
- Added `test_file_scraper.py` object call to "system" project scraping.
Updated `hipporead.py`:
- Removed …
> 1.0.7 update

- README.md
- autover.sh
- hippoproject.py
- hipporead.py
Mainly fixed js test file detection because it looked like a hassle to make 11 test files for today's project.
Added `autover.sh`:
- Development tool that changes versions code line in respective files with a script.
Updated `test_file_scraper.py`: 
- Added `.js` detection in test file names to create the test files for javascript.
> 1.0.8 update

- README.md
- hippoproject.py
- hipporead.py
- scrapers/high_scraper.py
- scrapers/low_scraper.py
- scrapers/test_file_scraper.py
Fixing major issue with html test file creation and adding a feature.
Added function that generates `check.sh`:
- Run `./check.sh` to check only required files.
Updated `low_scraper.py`:
- `check.sh` function added.
Updated `high_scraper.py`:
- `check.sh` function added.
Updated `test_file_scraper.py`:
- Added `.html` detection.
- Isolated `.html` scraping as it has different methods from the other file format scraping.
> 1.1.0 update

- README.md
- auth_data.json
- hippoproject.py
- hipporead.py
- scrapers/base_parse.py
- setup.sh
Updating onboarding process:
`setup.sh`:
- Fixed password special character escaping
- Creates auth_data.json if does not exist
`base_parse.py`:
- Returns error if auth_data.json does not exist
> 1.1.1 update

- .gitignore
- README.md
- hipporead.py
- scrapers/read_scraper.py
A new functionality was added. Now the readme.md also generates the resources (project links).  Some icons in the subtitles too.
> A new functionality was added. Now the readme also generates the resources (project links)
